-- multilanguage text table
-- if Yo want add your supported mother language, extend table and let me know, I will push it in the Git

-- Warm thanks to Francesco Salvi for the translation into Italian

local transtable        = { en = { wgname          = "Vario",
                                   menuname        = "Vario",
                                   VarioSensor     = "Height sensor",
                                   VertSensor      = "Vertical speed sensor",
                                   wgtsmall        = "Small Widget",
                                   badSensor       = "Bad sensor type",
                                   noTelemetry     = "No Telemetry",
                                   bgcolor         = "Select background color",
                                   showMinMax      = "Show min/max values",
                                   showAltNegative = "Show negative Altitude",
                                   showVScolored   = "Show vertical speed in color",
                                 },
                            cs = { wgname          = "Vario",
                                   menuname        = "Vário",
                                   VarioSensor     = "Senzor výšky",
                                   VertSensor      = "Senzor vertikální rychlosti",
                                   wgtsmall        = "Málo místa",
                                   badSensor       = "Špatně zvolený senzor",
                                   noTelemetry     = "Chybí telemetrie",
                                   bgcolor         = "Vyberte barvu pozadí",
                                   showMinMax      = "Zobrazit min/max hodnoty",
                                   showAltNegative = "Zobrazit záporné výšky",
                                   showVScolored   = "Zobrazit vertikální rychlost barevně",
                                 },
                            de = { wgname          = "Vario",
                                   menuname        = "Vário",
                                   VarioSensor     = "Höhensensor",
                                   VertSensor      = "Vertikaler Geschwindigkeitssensor",
                                   wgtsmall        = "Kleines Widget",
                                   badSensor       = "Schlechter Sensortyp",
                                   noTelemetry     = "Keine Telemetrie",
                                   bgcolor         = "Hintergrundfarbe auswählen",
                                   showMinMax      = "Min/Max Werte anzeigen",
                                   showAltNegative = "Negative Höhe anzeigen",                                   
                                   showVScolored   = "Vertikalgeschwindigkeit farbig anzeigen",
                                 },
                            it = { wgname          = "Vario",
                                   menuname        = "Vario",
                                   VarioSensor     = "Sensore altezza",
                                   VertSensor      = "Sensore velocità verticale",
                                   wgtsmall        = "Widget ridotto",
                                   badSensor       = "Tipo di sensore non valido",
                                   noTelemetry     = "Nessuna telemetria",
                                   bgcolor         = "Seleziona colore di sfondo",
                                   showMinMax      = "Mostra valori min/max",
                                   showAltNegative = "Mostra altitudine negativa",                                   
                                   showVScolored   = "Mostra la velocità verticale a colori",
                                 },                                 
                          }
                          
return {transtable = transtable}